name: flutter_application_recipebook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home_screen/category-beef.jpg
    - assets/home_screen/category-chicken.jpg
    - assets/home_screen/category-pork.jpg
    - assets/home_screen/category-seafood.jpg
    - assets/home_screen/recommendation-beefSteak.jpg
    - assets/home_screen/recommendation-carBonaRa.jpg
    - assets/home_screen/recommendation-grilledChicken.jpg
    - assets/home_screen/recommendation-salmon.jpg

    - assets/view_all_categories/1chicken.jpg
    - assets/view_all_categories/2pork.jpg
    - assets/view_all_categories/3beef.jpg
    - assets/view_all_categories/4seafood.jpg
    - assets/view_all_categories/5filipino.jpg
    - assets/view_all_categories/6italian.jpg
    - assets/view_all_categories/7mexican.jpg
    - assets/view_all_categories/8japanese.jpg
    - assets/view_all_categories/9snacks.jpg
    - assets/view_all_categories/10desserts.jpg

    - assets/recipes/r1.jpg
    - assets/recipes/r2.jpg
    - assets/recipes/r3.jpg
    - assets/recipes/r4.jpg
    - assets/recipes/r5.jpg
    - assets/recipes/r6.jpg
    - assets/recipes/r7.jpg
    - assets/recipes/r8.jpg
    - assets/recipes/r9.jpg
    - assets/recipes/r10.jpg
    - assets/recipes/r11.jpg
    - assets/recipes/r12.jpg
    - assets/recipes/r13.jpg
    - assets/recipes/r14.jpg
    - assets/recipes/r15.jpg
    - assets/recipes/r16.jpg
    - assets/recipes/r17.jpg
    - assets/recipes/r18.jpg
    - assets/recipes/r19.jpg
    - assets/recipes/r20.jpg
    - assets/recipes/r21.jpg
    - assets/recipes/r22.jpg
    - assets/recipes/r23.jpg
    - assets/recipes/r24.jpg
    - assets/recipes/r25.jpg
    - assets/recipes/r26.jpg
    - assets/recipes/r27.jpg
    - assets/recipes/r28.jpg
    - assets/recipes/r29.jpg
    - assets/recipes/r30.jpg
    - assets/recipes/r31.jpg
    - assets/recipes/r32.jpg
    - assets/recipes/r33.jpg
    - assets/recipes/r34.jpg
    - assets/recipes/r35.jpg
    - assets/recipes/r36.jpg
    - assets/recipes/r37.jpg
    - assets/recipes/r38.jpg
    - assets/recipes/r39.jpg
    - assets/recipes/r40.jpg
    - assets/recipes/r41.jpg
    - assets/recipes/r42.jpg
    - assets/recipes/r43.jpg
    - assets/recipes/r44.jpg
    - assets/recipes/r45.jpg
    - assets/recipes/r46.jpg
    - assets/recipes/r47.jpg
    - assets/recipes/r48.jpg
    - assets/recipes/r49.jpg
    - assets/recipes/r50.jpg
