name: flutter_application_recipebook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home_screen/category-beef.jpg
    - assets/home_screen/category-chicken.jpg
    - assets/home_screen/category-pork.jpg
    - assets/home_screen/category-seafood.jpg
    - assets/home_screen/recommendation-beefsteak.jpg
    - assets/home_screen/recommendation-carbonara.jpg
    - assets/home_screen/recommendation-grilledchicken.jpg

    - assets/view_all_categories/1chicken.jpg
    - assets/view_all_categories/2pork.jpg
    - assets/view_all_categories/3beef.jpg
    - assets/view_all_categories/4seafood.jpg
    - assets/view_all_categories/5filipino.jpg
    - assets/view_all_categories/6italian.jpg
    - assets/view_all_categories/7mexican.jpg
    - assets/view_all_categories/8japanese.jpg
    - assets/view_all_categories/9snacks.jpg
    - assets/view_all_categories/10desserts.jpg
